### ISSUE TITLE
Windows builds failing due to libclang v16

### ISSUE THREAD

**Issue by ianks** [oxidize-rb/actions#20]
Noticing that libclang 16 was published today sometime between ([old build](https://github.com/bytecodealliance/wasmtime-rb/actions/runs/4579552856/jobs/8087453358) .. [new build](https://github.com/bytecodealliance/wasmtime-rb/actions/runs/4584581454/jobs/8096161127)). I'm not 100% sure yet, but I _think_ this is a bindgen issue that may be fixed on `main`. Unfortunately, `v0.9` version of rb-sys cannot upgrade `bindgen` due to breaking MSRV changes. So we'll have to find another solution.

Awhile ago, I made a `libclang-rb` which packages native v14 binaries of libclang, so theoretically we should be able to hook that up. Something like:

```sh
$ gem install libclang
$ echo "LIBCLANG_PATH=$(ruby -rlibclang -e 'puts Libclang.libdir')" > $GITHUB_ENV
```

**Comment by ianks** [comment]
well, downgrading clang seems to fix one issue at least. however, now bindgen can't find `strings.h` when it used to before. it's unclear why on earth it can't be found now, despite using the same version of libclang that we were before (v15).

https://github.com/oxidize-rb/actions/actions/runs/4614267540/jobs/8157059868

**Comment by ianks** [comment]
any help on this would be much appreciated 🙏🏻

**Comment by ianks** [comment]
allegedly, `/mingw64/include/strings.h` exists... but even when i try to include it, it doesn't take.

**Comment by jbourassa** [comment]
I've been following along and I really thought the commit with `-I/mingw64/include/strings.h` was gonna work, 😕.

I installed an arm Windows on my Mac but did not manage to get things to build, the Microsoft C++ tooling for Windows wasn't available for arm. Might try a couple more things tomorrow.

The long feedback loop make it very painful to debug 😭.

**Comment by ianks** [comment]
I tried every possible way I could think of to include the directory... stumped.

```rust
clang_args.push("-I/mingw64/include".to_string());
clang_args.push("-IC:\\mingw64\\include".to_string());

clang_args.push("-I/msys64/include".to_string());
clang_args.push("-IC:\\msys64\\include".to_string());
```

**Comment by ianks** [comment]
And for record's sake, [here's the build where I confirmed the file exists](https://github.com/oxidize-rb/actions/actions/runs/4612635253/jobs/8153760976) with: `find / -name strings.h`

**Comment by MSP-Greg** [comment]
Newer Windows Rubies are ucrt64, older Rubies are mingw64.  So, new Rubies should really be using `ucrt64/include/strings.h`

**Comment by ianks** [comment]
Ok, [this CI run proves to me that `strings.h` does exist](https://github.com/oxidize-rb/rb-sys/actions/runs/4614858047), and we are indeed including the path. Something very unexpected is happening.

**Comment by ianks** [comment]
> I've been following along and I really thought the commit with `-I/mingw64/include/strings.h` was gonna work, 😕.
> 
> I installed an arm Windows on my Mac but did not manage to get things to build, the Microsoft C++ tooling for Windows wasn't available for arm. Might try a couple more things tomorrow.
> 
> The long feedback loop make it very painful to debug 😭.

Yes, I failed to get windows running on my mac as well, but even if I did I'm not sure how to create an environment similar to GHA. So here we are. Luckily, we have @MSP-Greg who has been super helpful with this stuff.

**Comment by jbourassa** [comment]
On Ruby 3.1, I get a different error when using `/ucrt64/include`:

```
BINDGEN_EXTRA_CLANG_ARGS="-I/ucrt64/include" bundle exec rake

[...]

thread 'main' panicked at 'generate bindings: ClangDiagnostic("C:/msys64/ucrt64/include\\stdlib.h:388:47: error: expected ';' after top level declarator\nC:/msys64/ucrt64/include\\stdlib.h:389:48: error: expected ';' after top level declarator\nC:/msys64/ucrt64/include\\stdlib.h:391:53: error: expected ';' after top level declarator\nC:/msys64/ucrt64/include\\stdlib.h:396:26: error: expected ';' after top level declarator\nC:/msys64/ucrt64/include\\stdlib.h:686:69: error: expected
[...]
```

Not sure if that's helpful.

**Comment by MSP-Greg** [comment]
Sorry.  A long day.  The full folder is `C:/msys64/mingw64/include`.  For Ruby 3.1 and later, it should be `C:/msys64/ucrt64/include`.  

Also, `msys64/include` does not exist.

**Comment by ianks** [comment]
> Sorry. A long day. The full folder is `C:/msys64/mingw64/include`. For Ruby 3.1 and later, it should be `C:/msys64/ucrt64/include`.
> 
> Also, `msys64/include` does not exist.

Trying this in https://github.com/oxidize-rb/rb-sys/actions/runs/4614987830

**Comment by ianks** [comment]
Ok, new error. Now we're cookin' with gas. `mmintrin.h` stuff.

**Comment by ianks** [comment]
I think I'm going to try to get some sleep here. But we need to figure this out tomorrow. I'd really like to find the root cause, because currently, I'm just firing off commits and hoping they work 😞

**Comment by MSP-Greg** [comment]
> I think I'm going to try to get some sleep here

I was about to say the same.

> But we need to figure this out tomorrow.

I'll be glad to help anyway I can.  I'm Central...

**Comment by ianks** [comment]
@MSP-Greg since you are more in tune with the windows ecosystem, maybe you could investigate if any runner actions changes got deployed that might affect this?

It seems strange to me that we now need to include `-IC:/msys2/{mingw64,ucrt64}` for clang to find the system paths when things "Just Worked" before. And I'm not sure where to start looking...

**Comment by ianks** [comment]
Also, I saw somewhere that there is some type of `clang64` msys environment... I wonder if that's what we really want here?

**Comment by ianks** [comment]
I stumbled across https://github.com/rust-lang/rust-bindgen/issues/1760#issuecomment-612709054, so I added a [(fairly ugly) commit](https://github.com/oxidize-rb/rb-sys/pull/190/commits/0b0feac3e56446100d086966d21f45b29ba92f09) to configure the sysroot and explicit clang target for bindgen. Let's see what happens.

**Comment by ianks** [comment]
I noticed this line is not working as expected....

```
echo "BINDGEN_EXTRA_CLANG_ARGS=$((gcm clang).source -replace "bin\clang.exe","include")" >> $env:GITHUB_ENV
```

But in the environment I see: `BINDGEN_EXTRA_CLANG_ARGS: C:\Program Files\LLVM\bin\clang.exe`...

**Comment by MSP-Greg** [comment]
Sorry, AFK

Try
```ps
echo "BINDGEN_EXTRA_CLANG_ARGS=$($(where.exe clang).replace('bin\clang.exe','include'))" >> $env:GITHUB_ENV
```

**Comment by ianks** [comment]
@MSP-Greg how did the builds go for https://github.com/oxidize-rb/actions/issues/20#issuecomment-1497709981

**Comment by ianks** [comment]
So after including the system paths (`c:/msys2/{mingw64,ucrt64`), we've made some progress. Now, [it's having trouble finding `mm_malloc.h`](https://github.com/oxidize-rb/rb-sys/actions/runs/4631857338/jobs/8195229503). Anyone know what that is?

**Comment by ianks** [comment]
So they exist on the runner as well. I'm wondering why they aren't found by default with clang-15? Do I need to add clang-15 to my path?

```
/mingw64/lib/gcc/x86_64-w64-mingw32/12.2.0/include/mm_malloc.h
/mingw64/opt/llvm-15/lib/clang/15.0.7/include/mm_malloc.h
/mingw64/opt/llvm-15/lib/clang/15.0.7/include/ppc_wrappers/mm_malloc.h
```

**Comment by ianks** [comment]
Ok so it looks like `clang-15` installs to `/mingw64/opt/llvm-15/`, where as `clang` installs to `/mingw64/`. I bet that screwed everything up.

**Comment by MSP-Greg** [comment]
Not sure.  That might be because clang (16) is the default package, and clang-15 is optional.

**Comment by ianks** [comment]
LFG https://github.com/oxidize-rb/rb-sys/actions/runs/4632322440/jobs/8196289444

**Comment by MSP-Greg** [comment]
That's nice to see.
1. Noticed that all the ucrt builds (and mswin) fail.  Maybe an issue with `stable-x86_64-pc-windows-gnu` being mingw?
2. Any thoughts on whether to try clang (16)?

**Comment by ianks** [comment]
@MSP-Greg Here's the diff I think _should_ do it https://github.com/oxidize-rb/actions/pull/22/files#diff-458e5469c2f2c350461246fca9a5596e0d82b7de7aa0895555fff27b17ed952a

**Comment by ianks** [comment]
kind of annoying that clang-15 is 2gb to install, and pretty slow. but I can live with that for now.
