### ISSUE TITLE
Don't know how to build task 'native:arm64-darwin'

### ISSUE THREAD

**Issue by ball-hayden** [oxidize-rb/actions#24]
Looking forward to getting started with `rb-sys`, but I'm having an issue while cross-compiling.

Here's my Rakefile:

```
# frozen_string_literal: true

require "bundler/gem_tasks"
require "rb_sys/extensiontask"
require "rspec/core/rake_task"
require "rubocop/rake_task"

RSpec::Core::RakeTask.new(spec: %i[compile:dev])
RuboCop::RakeTask.new

GEMSPEC = Gem::Specification.load("datafile_ruby.gemspec")

RbSys::ExtensionTask.new("datafile_ruby", GEMSPEC) do |ext|
  ext.lib_dir = "lib/datafile_ruby"
end

task build: %i[compile]
task default: %i[compile spec rubocop]
```

I can build fine locally, but using https://github.com/oxidize-rb/actions/tree/main/cross-gem I get the following:

```
...
no configuration section for specified version of Ruby (rbconfig-arm64-darwin-3.1.4)
no configuration section for specified version of Ruby (rbconfig-arm64-darwin-3.2.2)
rake aborted!
Don't know how to build task 'native:arm64-darwin' (See the list of available tasks with `rake --tasks`)
```

**Comment by gjtorikian** [comment]
Could you try adding the following lines to your Rakefile:

```
desc "Build native extension for a given platform (i.e. `rake 'native[x86_64-linux]'`)"
task :native, [:platform] do |_t, platform:|
  sh "bundle", "exec", "rb-sys-dock", "--platform", platform, "--build"
end
```

And add + install `rb-sys-dock` to your gemfile?

**Comment by gjtorikian** [comment]
Gah, got the gem name wrong. It's [`rake-compile-dock`](https://rubygems.org/gems/rake-compiler-dock). 

I _think_ simply including it as a dev dependency automagically includes the necessary Rake tasks, because it is the one that does define the `native:{platform}` task that's missing: https://github.com/rake-compiler/rake-compiler-dock#add-to-your-rakefile

Admittedly, it's been some time since I set a project up from scratch! My tasks are defined exactly as yours are, though. If you have a repo I can clone it and poke around, too.

**Comment by ball-hayden** [comment]
Thanks @gjtorikian.
There's a minimal reproduction at https://github.com/ball-hayden/rb-sys-repro/pull/1
I'll give you collaborator access to that repo so you can play around if you like.

I've tried adding the `rake-compiler-dock` gem as well - that doesn't seem to help at all.

**Comment by ball-hayden** [comment]
Okay - I think I've worked out some of the problem.
The docker image seems to have `RAKE_EXTENSION_TASK_NO_NATIVE=true` set, which causes `rake-compiler` to skip defining the native tasks.

**Comment by ball-hayden** [comment]
Some success - I was able to get it going by skipping the `rb-sys-dock` tool and using the container directly:

https://github.com/ball-hayden/rb-sys-repro/pull/2

**Comment by ball-hayden** [comment]
Okay... Got it.

It's needing `ext.cross_compile = true` set in the `Rakefile`, and the ruby version needs to be one of those defined in https://cache.ruby-lang.org/pub/misc/ci_versions/cruby.json - including the patch version confuses it.

**Comment by ball-hayden** [comment]
I appreciate your prompt help @gjtorikian, and ❤️ for the work you've done with oxidize-rb.

**Comment by gjtorikian** [comment]
Thanks, but most of the credit for oxidize goes to @ianks!  

Would you be willing to update documentation/README to help others alleviate this issue. It's strange, I haven't set `cross_compile` in any of my projects that embed Rust in Ruby. I wonder if I'm running on older versions of a dependency that now requires this?

**Comment by taylorthurlow** [comment]
Yeah this is the same problem I'm running into, but clearly the `cross_compile` option is not the solution for me. I'm having trouble interpreting what @ball-hayden means by the Ruby version needing to be one from the referenced list. I'm not even clear what Ruby version we're talking about here, let alone where to set it.

I've tried `RUBY_CC_VERSION=3.0` in a few places and it seems to generally respond to those changes but it hasn't actually fixed anything.

In the Docker context all of the `native` prefixed tasks don't appear to exist. So far it's also not clear to me how these tasks or built or where, but they don't appear anywhere unless I add the task to my Rakefile by hand, as @gjtorikian suggested earlier. There's also the distinction between rake tasks with a `native` namespace and an actual name of the platform, vs. the `native` task with a string platform name argument.

Either way, I'm getting this in every scenario:

```
no configuration section for specified version of Ruby (rbconfig-x86_64-linux-3.0)
rake aborted!
Don't know how to build task 'native:x86_64-linux' (See the list of available tasks with `rake --tasks`)
```

**Comment by taylorthurlow** [comment]
Alright, well I don't really have an explanation for why this is the case, but as far as I could tell, the native tasks don't get generated because `@gemspec` is nil, which after digging around in `rake-compiler` source just seems to be the case because it's not passed into the `RbSys::ExtensionTask` initializer in my Rakefile. Changing it to this and things are building:

```
spec = Gem::Specification.load("rust_json_schema.gemspec")]
RbSys::ExtensionTask.new("rust_json_schema", spec) do |ext|
  ext.lib_dir = "lib/rust_json_schema"
  ext.cross_compile = true
end
```
