### ISSUE TITLE
Missing rb-sys 0.9.100 images

### ISSUE THREAD

**Issue by gjtorikian** [oxidize-rb/actions#41]
From https://github.com/gjtorikian/selma/actions/runs/10238916228/job/28323948017: 

```
+ rb-sys-dock --platform arm64-darwin --directory . --ruby-versions 3.1,3.2,3.3 --build
::info::🐳 Building for Ruby requested versions: ["3.1.0", "3.2.0", "3.3.0"]
::info::🐳 Downloading container "rbsys/arm64-darwin:0.9.100", this might take awhile...
Error response from daemon: manifest for rbsys/arm64-darwin:0.9.100 not found: manifest unknown: manifest unknown
```

Looking on [Dockerhub](https://hub.docker.com/r/rbsys/aarch64-linux-musl/tags?page=&page_size=&ordering=&name=0.9.), there's only `cache-0.9.100` tagged.

**Comment by gjtorikian** [comment]
@ianks bleh sorry for the direct ping but I just discovered you’re not watching the repo 😅

I’m pretty sure the issue is in rb-sys, but after scouring the 0.9.100 build logs I was totally unable to find a root cause.

**Comment by ianks** [comment]
looks like the build didnt trigger from the version tag, which i may have messed up. building now https://github.com/oxidize-rb/rb-sys/actions/runs/10324115253

**Comment by gjtorikian** [comment]
thanks dude 🙏

**Comment by gjtorikian** [comment]
Images found!

For my own edification, what was the issue? I struggled to find a source.

**Comment by ianks** [comment]
i think i f'd up the GHA trigger for `v*` tags or something?

**Comment by ianks** [comment]
https://github.com/oxidize-rb/rb-sys/commit/fc040296ca7b7849594c458ef5d96b7a298b2ace
